import type { Metadata } from "next";
import "./globals.css";
import { LoadingProvider } from "@/app/context/LoadingContext";
import Loading from "@/app/components/Loading";
import MainMenu from "./components/MainMenu";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body>
                <MainMenu />
                <LoadingProvider>
                    <Loading />
                    {children}
                </LoadingProvider>
            </body>
        </html>
    );
}
